# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fea6677f838b56f0d2d22e4288b7378cab6e4c1ef61221de3b898c3fd6325174b881a793a7d9babb0008fcc3bbfc6baf0f6d0cfe877a27834e770c895178029c

test:
  secret_key_base: 99a3eb608c6bc32cf424e4be5654bd3490e0bfd42b4a5120483f5130f91543f6d6634a2b29cfe655d16b58e2daaa7e6713ec5573f608fe050e61d1c92f88e19f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
